type Measure={metric:string;value:string;unit:string;scale?:string;operator:string;denominator:string;measurement_as_of?:string|null;denominator_as_of?:string|null};
type Fact={id:string;counterparty_name:string;counterparty_entity_id:string|null;identity_kind:string;role:string;relationship:string;fiscal_year:number|null;period_end:string|null;observation_date:string|null;observation_basis?:string;count:number|null;measurement_basis:string;segment:string|null;estimated:boolean;measures:Measure[];scope_note:string;evidence:{passage_id:string;quote:string}[]};
const metricNames:Record<string,string>={revenue_share:'收入占比',receivables_share:'应收账款占比',revenue_amount:'客户收入',procurement_share:'采购占比',cost_of_sales_share:'占销售成本比例',cost_and_operating_expense_share:'占收入成本及经营费用比例',procurement_commitment_amount:'未来采购承诺',financial_guarantee_maximum_payment:'财务担保潜在支付上限',restricted_investment_amount:'协议约定的受限投资余额',procurement_amount:'采购金额',beneficial_shares:'实益持股',ownership_share:'持股比例',voting_power_share:'投票权比例',annualized_recurring_revenue:'年化经常性收入',annualized_recurring_revenue_share:'年化经常性收入占比'};
const relationNames:Record<string,string>={direct_customer:'直接客户',indirect_customer:'间接客户',customer:'客户',supplier:'供应商',beneficial_owner:'实益拥有人'};
export default function CounterpartyDisclosure({row,onSource,onEntity}:{row:Record<string,unknown>;onSource:(id:string)=>void;onEntity:(id:string)=>void}){
  const facts=(row.structured_facts||[]) as Fact[];
  const reviewedEmpty=row.extraction_status==='checked_no_explicit_fact';
  return <article className="cw-counterparty-report">
    <h3>{String(row.title)}</h3>
    <p className="cw-caption">{row.published_at?'发布 '+String(row.published_at):row.known_as_of?`截至 ${String(row.known_as_of)} 已获取，发布日期待核`:'发布日期待核'} · {facts.length?`${facts.length} 条结构化记录`:reviewedEmpty?'已核查本来源范围':'尚无结构化记录'}</p>
    {facts.length?<div className="cw-table"><table><thead><tr><th>对象与关系</th><th>职责 / 范围</th><th>期间 / 截至日</th><th>已披露数值</th><th>口径与依据</th></tr></thead><tbody>{facts.map(f=><tr key={f.id}>
      <td>{f.counterparty_entity_id?<button onClick={()=>onEntity(f.counterparty_entity_id!)}>{f.counterparty_name}</button>:<strong>{f.counterparty_name}</strong>}<small className="cw-metric-code">{relationNames[f.relationship]||f.relationship}{f.identity_kind==='anonymous'?' · 匿名':f.identity_kind==='aggregate'?' · 合计':f.identity_kind==='population'?' · 全体范围':''}</small></td>
      <td>{f.role}{f.segment&&<small className="cw-metric-code">{f.segment}</small>}</td>
      <td>{f.observation_basis==='conditional_post_transaction'?'条件情景 · 交易完成后':f.fiscal_year?`FY${f.fiscal_year}`:''}{(f.observation_date||f.period_end)&&<small className="cw-metric-code">{f.observation_date?'截至 ':'报告期末 '}{f.observation_date||f.period_end}</small>}</td>
      <td>{f.measures.length?f.measures.map((m,i)=><div key={i}><strong>{metricNames[m.metric]||m.metric} {m.operator==='='?'':m.operator==='approximately'?'约 ':m.operator}{Number(m.value).toLocaleString('zh-CN',{maximumFractionDigits:4})}{m.unit==='percent'?'%':m.unit==='shares'?' 股':` ${m.scale && m.scale!=='1' ? m.scale+' × ' : ''}${m.unit}`}</strong><small className="cw-metric-code">{m.denominator}</small>{m.measurement_as_of&&<small className="cw-metric-code">数值截至 {m.measurement_as_of}</small>}{m.denominator_as_of&&<small className="cw-metric-code">分母截至 {m.denominator_as_of}</small>}</div>):'该项未列金额或占比'}{f.measurement_basis==='each'&&<small className="cw-metric-code">共 {f.count} 个对象，数值为各自占比</small>}{f.estimated&&<small className="cw-metric-code">公司估计</small>}</td>
      <td><details><summary>适用条件与口径说明</summary><p>{f.scope_note}</p></details><details><summary>核对原文依据</summary>{f.evidence.map((e,i)=><blockquote key={i}>{e.quote}</blockquote>)}</details></td>
    </tr>)}</tbody></table></div>:<p className="cw-extraction-pending">{String(row.extraction_note||'尚未完成结构化提取；这不等于公司未披露。')}</p>}
    {Boolean(row.source_id)&&<button className="cw-report-source" onClick={()=>onSource(String(row.source_id))}>查看完整原文与表格</button>}
  </article>;
}
