import {useEffect,useRef,useState} from 'react';
import {useSearchParams} from 'react-router';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import {ArrowRight,BookOpen,Check,ChevronDown,Database,FileText,FolderOpen,MessageSquare,Plus,Save,Search,Settings2,X} from 'lucide-react';
import {assetRequest as request,type Asset,type AssetVersion,type AssetContext,type AssetProfile,type AssetRef,type SourceCapture} from '../api/assetWorkspace';
import './asset-workspace.css';
import {SourceCapturePanel,CapturedFinancialTable} from './SourceCapturePanel';
import {ProjectStorageUsage} from './ProjectStorageUsage';
import ConversationWorkspace from './ConversationWorkspace';
import {TaskAssetUpdates} from './TaskAssetUpdates';

type Reading={capture?:SourceCapture;version:AssetVersion;editable:boolean;text:string;truncated:boolean;needs_vision?:boolean;concepts?:{taxonomy:string;tag:string;label:string}[];concept_total?:number};
const valid=(v:AssetVersion)=>v.access_status==='active'&&v.status==='complete';
const roleName={document:'资料',report:'研究成果',database:'数据库'};

export default function ProjectAssetWorkspace(){
  const [params,setParams]=useSearchParams();const project=params.get('project')||'';
  const [projects,setProjects]=useState<{id:string;name:string}[]>([]),[assets,setAssets]=useState<Asset[]>([]);
  const [selected,setSelected]=useState<AssetVersion|null>(null),[reading,setReading]=useState<Reading|null>(null);
  const [query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [profile,setProfile]=useState<AssetProfile>({version:0,body:''}),[profileText,setProfileText]=useState('');
  const [question,setQuestion]=useState(''),[context,setContext]=useState<AssetContext|null>(null);
  const [editing,setEditing]=useState(false),[title,setTitle]=useState(''),[text,setText]=useState('');
  const [assistantOpen,setAssistantOpen]=useState(!!params.get('assistant')),[history,setHistory]=useState(false);
  const assistant=params.get('assistant')||'';
  const [conversations,setConversations]=useState<{thread_id:string;title:string;asset_project_id?:string}[]>([]);
  const [memoryHistory,setMemoryHistory]=useState<{version:number;body:string;updated_at:string}[]>([]);
  const setAssistant=(id:string)=>setParams(current=>{if(id)current.set('assistant',id);else current.delete('assistant');return current;});
  useEffect(()=>{let alive=true;if(assistantOpen)void request<typeof conversations>('conversations').then(rows=>{if(alive)setConversations(rows.filter(r=>r.asset_project_id===project));}).catch(e=>setError(e.message));return()=>{alive=false;};},[assistantOpen,assistant,project]);
  const [visibleCount,setVisibleCount]=useState(30);
  useEffect(()=>setVisibleCount(30),[project,query,filter]);
  const [noteEditing,setNoteEditing]=useState(false),[chosen,setChosen]=useState<AssetRef[]>([]);
  const memoryDialog=useRef<HTMLDialogElement>(null);
  const currentGroup=assets.find(a=>a.asset_id===selected?.ref.asset_id&&a.kind===selected?.ref.kind);
  const filtered=assets.filter(a=>(filter==='all'||a.current.role===filter)&&a.current.title.toLowerCase().includes(query.toLowerCase()));
  const load=async()=>{if(!project)return;const data=await request<{items:Asset[]}>(`asset-workspace/projects/${project}`);setAssets(data.items);return data.items;};
  useEffect(()=>{void Promise.all([request<{projects:{id:string;name:string}[]}>('projects'),request<AssetProfile>('asset-workspace/profile')]).then(([index,p])=>{setProjects(index.projects);setProfile(p);setProfileText(p.body);if(!project&&index.projects.length)setParams(current=>{current.set('project',index.projects[0].id);return current;});}).catch(e=>setError(e.message));},[]);
  useEffect(()=>{let alive=true;setAssets([]);setSelected(null);setReading(null);setEditing(false);setNoteEditing(false);setChosen([]);setContext(null);setHistory(false);setError('');setQuestion('');
    if(project){setBusy(true);void request<{items:Asset[]}>(`asset-workspace/projects/${project}`).then(data=>{if(alive){setAssets(data.items);if(!params.get('context'))setSelected(data.items.flatMap(a=>a.versions).find(v=>v.ref.version_id===params.get('asset'))||data.items[0]?.current||null);}}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setBusy(false);});}return()=>{alive=false;};},[project]);
  useEffect(()=>{let alive=true;setReading(null);setHistory(false);if(selected){setBusy(true);void request<Reading>('asset-workspace/read','POST',selected.ref).then(value=>{if(alive)setReading(value);}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setBusy(false);});}return()=>{alive=false;};},[selected?.ref.version_id]);
  useEffect(()=>{const id=params.get('context');if(!id)return;let alive=true;void request<AssetContext>(`asset-workspace/contexts/${id}`).then(async c=>{if(!alive)return;if(c.refs[0].project_id!==project){setError('交接记录与当前项目不一致，请从原任务返回。');return;}setContext(c);setQuestion(c.question);setChosen(c.refs);const data=await request<{items:Asset[]}>(`asset-workspace/projects/${project}`);if(alive)setSelected(data.items.flatMap(a=>a.versions).find(v=>v.ref.version_id===c.refs[0].version_id)||null);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[params.get('context'),project]);
  function clearContext(version?:string){setContext(null);if(params.has('context')||version)setParams(current=>{current.delete('context');if(version)current.set('asset',version);return current;},{replace:true});}
  function choose(v:AssetVersion){if(editing||noteEditing){setError('请先保存或放弃当前修改，再切换资料。');return;}setError('');setSelected(v);clearContext(v.ref.version_id);setNotice('');}
  async function saveDocument(){setBusy(true);setError('');try{const result=await request<{document_id:string}>('asset-workspace/documents','POST',{project_id:project,title,text,...(reading&&selected?{base_ref:selected.ref}:{})});const rows=await load();setEditing(false);clearContext(result.document_id);const version=rows?.flatMap(a=>a.versions).find(v=>v.ref.version_id===result.document_id)||null;setSelected(version);if(version)setChosen(refs=>refs.map(r=>r.asset_id===version.ref.asset_id&&r.kind===version.ref.kind?version.ref:r));setContext(null);setNotice('已保存新版本。已有任务继续保留它们原先采用的版本。');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function prepare(target:'research'|'conversation'|'save'){
    if(!selected)return;const refs=chosen.length?chosen:[selected.ref];setBusy(true);setError('');setNotice('');
    try{let c=context;if(!c||c.question!==question||JSON.stringify(c.refs)!==JSON.stringify(refs)){c=await request<AssetContext>('asset-workspace/contexts','POST',{schema_version:'asset_context.v1',question,refs,memory_version:profile.version});setContext(c);const contextId=c.context_id;setParams(current=>{current.set('project',project);current.set('context',contextId);return current;});}
      if(target==='save'){setNotice('问题与所选资料版本已保存，尚未调用模型。');return;}
      const endpoint=target==='research'?'research-sessions':'conversations/drafts';
      const body=target==='research'?{mode:'research',defer_start:true,title:question.slice(0,80),asset_context_id:c.context_id}:{title:question.slice(0,80),asset_context_id:c.context_id};
      const result=await request<{thread_id:string}>(endpoint,'POST',body);
      if(target==='conversation')setAssistant(result.thread_id);
      else window.location.assign(`/workspace/session?thread=${result.thread_id}&view=graph`);
    }catch(e){setError((e as Error).message);}finally{setBusy(false);}
  }
  return <div className={`aw-shell ${assistantOpen?'':'aw-assistant-closed'}`}>
    <header className="aw-top"><span>项目资料 · 阅读与编辑</span><button className="aw-memory-trigger" onClick={()=>{setProfileText(profile.body);memoryDialog.current?.showModal();}}><Settings2 size={16}/>我的记忆</button><button onClick={()=>setAssistantOpen(!assistantOpen)}><MessageSquare size={16}/>围绕资料提问</button></header>
    <aside className="aw-nav"><div className="aw-nav-title"><FolderOpen size={16}/><span>研究资产</span></div><label className="aw-project-label">当前项目<select aria-label="资产项目" value={project} disabled={busy||editing||noteEditing} onChange={e=>setParams(current=>{current.set('project',e.target.value);current.delete('asset');current.delete('context');current.delete('assistant');return current;})}><option value="">选择项目</option>{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label>
      <label className="aw-search"><Search size={16}/><input aria-label="搜索资产" placeholder="搜索资产名称" value={query} onChange={e=>setQuery(e.target.value)}/></label>
      <div className="aw-filters" aria-label="资产分类">{[['all','全部'],['document','资料'],['report','成果'],['database','数据']].map(([id,label])=><button key={id} aria-pressed={filter===id} onClick={()=>setFilter(id)}>{label}</button>)}</div>
      <div className="aw-asset-list">{filtered.slice(0,visibleCount).map(a=><div className="aw-selectable-asset" key={`${a.kind}:${a.asset_id}`}>{assistantOpen&&<input type="checkbox" aria-label={`用于研究 ${a.current.title}`} disabled={busy||editing||noteEditing||!valid(a.current)} checked={chosen.some(r=>r.asset_id===a.asset_id&&r.kind===a.kind)} onChange={e=>{setChosen(refs=>e.target.checked?[...refs,selected?.ref.asset_id===a.asset_id?selected.ref:a.current.ref]:refs.filter(r=>r.asset_id!==a.asset_id||r.kind!==a.kind));clearContext();}}/>}<button className={a.asset_id===selected?.ref.asset_id?'selected':''} onClick={()=>choose(a.current)}>{a.kind==='sec'?<Database size={18}/>:a.current.role==='report'?<BookOpen size={18}/>:<FileText size={18}/>}<span><strong>{a.current.title}</strong><small>{roleName[a.current.role]} · v{a.current.sequence}{!valid(a.current)?' · 暂不可用':''}</small></span></button></div>)}{filtered.length>visibleCount&&<button onClick={()=>setVisibleCount(n=>n+30)}>显示更多资料（{visibleCount} / {filtered.length}）</button>}{!busy&&!filtered.length&&<p className="aw-muted">{project?'还没有这类资产。可以添加资料，或调整筛选。':'先创建或选择一个项目。'}</p>}</div>
      <button className="aw-add" disabled={!project||busy||editing||noteEditing} onClick={()=>{setSelected(null);setReading(null);setTitle('');setText('');setContext(null);setEditing(true);}}><Plus size={16}/>新建笔记</button>
      <ProjectStorageUsage project={project} revision={assets.reduce((n,a)=>n+a.versions.length,0)}/><div className="aw-connectors"><a href={project?`/workspace/session?view=project&project=${project}`:'/workspace/session'}>导入资料与管理项目 <ArrowRight size={14}/></a></div>
    </aside>
    <main className="aw-main"><div className="aw-breadcrumb">{projects.find(p=>p.id===project)?.name||'我的资产'}<span>/</span>{editing?'编辑资产':selected?roleName[selected.role]:'开始积累'}</div>
      {error&&<p className="aw-alert" role="alert">{error}</p>}{notice&&<p className="aw-notice" role="status"><Check size={16}/>{notice}</p>}{busy&&<p role="status" className="aw-muted">正在读取或保存…</p>}
      {editing?<section className="aw-editor"><h1>{reading?'修订资料':'新建研究笔记'}</h1><p className="aw-muted">保存为独立版本。你的判断与假设会保留为用户内容。</p><label>标题<input aria-label="资产标题" value={title} maxLength={120} onChange={e=>setTitle(e.target.value)}/></label><label>内容<textarea aria-label="资产内容" value={text} maxLength={100000} onChange={e=>setText(e.target.value)} placeholder="记下问题、判断、依据与仍需核查的假设…"/></label><div className="aw-actions"><button className="aw-primary" disabled={busy||!title.trim()||!text.trim()} onClick={()=>void saveDocument()}><Save size={16}/>保存版本</button><button disabled={busy} onClick={()=>{setEditing(false);setError('');}}>放弃修改</button></div></section>:
      selected?<><header className="aw-document-head"><div><span className="aw-tag">{roleName[selected.role]}</span><h1>{selected.title}</h1><p>v{selected.sequence} · 保存于 {new Date(selected.created_at).toLocaleDateString('zh-CN')}{!valid(selected)&&' · 使用受限'}</p></div><div className="aw-actions"><button disabled={busy||!reading?.editable} onClick={()=>{setTitle(selected.title);setText(reading!.text);setEditing(true);}}>编辑</button><button aria-expanded={history} onClick={()=>setHistory(!history)}>版本 <ChevronDown size={14}/></button></div></header>
        {reading?.capture&&<SourceCapturePanel key={selected.ref.version_id} capture={reading.capture} reference={selected.ref} onEditing={setNoteEditing} onSaved={async id=>{const rows=await load();const version=rows?.flatMap(a=>a.versions).find(v=>v.ref.version_id===id);if(version){setSelected(version);setChosen(refs=>refs.map(r=>r.asset_id===version.ref.asset_id?version.ref:r));}clearContext(id);setNotice('批注已保存新版本，来源内容未修改。已有任务继续保留原版本。');}}/>}
        {history&&<div className="aw-history" aria-label="资产版本">{currentGroup?.versions.map(v=><button key={v.ref.version_id} aria-pressed={v.ref.version_id===selected.ref.version_id} disabled={busy||noteEditing} onClick={()=>choose(v)}>v{v.sequence} · {new Date(v.created_at).toLocaleString('zh-CN')} · {valid(v)?'可用':v.status==='failed'?'同步失败':'使用受限'}</button>)}</div>}
        {selected.ref.version_id!==currentGroup?.current.ref.version_id&&<p className="aw-notice">正在查看历史版本。准备任务时会明确绑定这一版。</p>}
        {reading?.truncated&&<p className="aw-notice">当前仅预览部分内容，请到资料管理中下载完整原件。</p>}{reading?.needs_vision&&<p className="aw-notice">包含图片或扫描页，尚未识别的部分不会显示为已读取内容。</p>}
        <article className="aw-reading" aria-label="资产正文">{reading?.capture?.rows?<CapturedFinancialTable rows={reading.capture.rows}/>:reading?.concepts?<><h2>已保存的财务指标目录</h2><p>共 {reading.concept_total} 个原始指标，下面展示前 {reading.concepts.length} 个。保留原标签；并非都已映射成研究指标。</p><div className="aw-concepts">{reading.concepts.map(c=><div key={`${c.taxonomy}:${c.tag}`}><strong>{c.label}</strong><small>{c.taxonomy}:{c.tag}</small></div>)}</div><a href={`/workspace/session?view=project&project=${project}`}>查看期间、原值与单位 →</a></>:<ReactMarkdown remarkPlugins={[remarkGfm]} skipHtml components={{img:({alt})=><span>{alt}</span>}}>{reading?.text||(!busy?'当前没有可读取正文。':'')}</ReactMarkdown>}</article>
        <footer className="aw-reading-footer"><span>来源与版本始终保留</span><a href={`/workspace/session?view=project&project=${project}`}>资料管理与原件</a></footer></>:
      <section className="aw-empty"><div><BookOpen size={30}/></div><h1>让研究从已有积累开始</h1><p>选择一份资料阅读，维护自己的判断，或带着问题进入研究。</p><button className="aw-primary" disabled={!project||busy} onClick={()=>{setTitle('');setText('');setEditing(true);}}>写下第一条研究笔记</button><a href="/workspace/session">进入研究工作台</a></section>}
    </main>
    <aside className="aw-assistant" aria-label="资产小助手"><header><div><MessageSquare size={18}/><strong>资产小助手</strong></div><button aria-label="收起资产助手" onClick={()=>setAssistantOpen(false)}><X size={17}/></button></header>
      <div className="aw-conversation-picker"><select aria-label="项目资产对话" value={assistant} onChange={e=>setAssistant(e.target.value)}><option value="">围绕所选资料新建对话</option>{conversations.map(c=><option key={c.thread_id} value={c.thread_id}>{c.title}</option>)}</select>{assistant&&<button onClick={()=>setAssistant('')}>新问题</button>}</div>
      {assistant?<><TaskAssetUpdates thread={assistant} selected={selected} refreshKey={assets.reduce((n,a)=>n+a.versions.length,0)} surface="conversations"/><div className="aw-embedded-conversation"><ConversationWorkspace key={assistant} embedded={{thread:assistant,onThread:setAssistant,onRemember:value=>{setProfileText(value||profile.body);memoryDialog.current?.showModal();},onResearch:async(checkpoint,question)=>{const c=await request<AssetContext>(`conversations/${assistant}/research-context`,'POST',{checkpoint_id:checkpoint,question});const result=await request<{thread_id:string}>('research-sessions','POST',{mode:'research',defer_start:true,title:question.slice(0,80),asset_context_id:c.context_id});window.location.assign(`/workspace/session?thread=${result.thread_id}&view=graph`);}}}/></div></>:<><div className="aw-assistant-body"><span className="aw-tag">问题准备</span><h2>围绕这份资产，<br/>继续想一步。</h2><p>选择资料后在这里连续问答，需要深入调查时连同讨论交给研究团队。</p>
      {selected&&<div className="aw-context-card"><small>本次采用 {chosen.length||1} 份资料 · 固定版本</small>{(chosen.length?chosen:[selected.ref]).map(r=>{const v=assets.find(a=>a.asset_id===r.asset_id&&a.kind===r.kind)?.versions.find(v=>v.ref.version_id===r.version_id);return <div key={r.version_id}><strong>{v?.title||'所选资料'}</strong><span>v{v?.sequence||'—'}</span></div>;})}</div>}
      {profile.body?<div className="aw-profile-summary"><small>我的记忆 · v{profile.version}</small><p>{profile.body}</p></div>:<button className="aw-link" onClick={()=>memoryDialog.current?.showModal()}>添加你的关注方向与阅读习惯</button>}
      {context&&<div className="aw-saved-context"><Check size={16}/><div><strong>问题已保存</strong><p>{context.question}</p><small>个人记忆快照 v{context.memory.version}</small>{context.source_status?.some(s=>s.status!=='current')&&<p>部分资料已有更新或暂不可用，请核对当前选择。</p>}</div></div>}
    </div><form className="aw-compose" onSubmit={e=>{e.preventDefault();void prepare('save');}}><label htmlFor="aw-question">想了解什么？</label><textarea id="aw-question" aria-label="资产问题" value={question} maxLength={4000} onChange={e=>{setQuestion(e.target.value);clearContext();}} placeholder="例如：这个判断有哪些依据？哪些假设还需要核查？"/><button disabled={busy||editing||noteEditing||!selected||!valid(selected)||question.trim().length<10} type="submit">保存问题</button><div className="aw-handoff"><button disabled={busy||editing||noteEditing||!selected||!valid(selected)||question.trim().length<10} type="button" onClick={()=>void prepare('conversation')}>准备助手对话</button><button className="aw-primary" disabled={busy||editing||noteEditing||!selected||!valid(selected)||question.trim().length<10} type="button" onClick={()=>void prepare('research')}>交给研究团队 <ArrowRight size={15}/></button></div><small>准备后可在这里发送消息；发送才调用模型。研究先进入草稿。</small></form></>}</aside>
    <dialog ref={memoryDialog} className="aw-memory-dialog" aria-label="我的记忆"><header><h2>让助手更了解你</h2><button aria-label="关闭我的记忆" onClick={()=>memoryDialog.current?.close()}><X size={18}/></button></header><p>由你主动维护。用于理解偏好与关注点，不作为已核验事实；已准备的任务保留原记忆快照。</p><textarea aria-label="个人长期记忆" value={profileText} maxLength={4000} onChange={e=>setProfileText(e.target.value)} placeholder="例如：关注企业现金创造能力。回答先给结论，再说明来源、期间和反证。"/><small>当前版本 v{profile.version} · 清空后保存可移除当前内容</small><div className="aw-actions"><button className="aw-primary" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const p=await request<AssetProfile>('asset-workspace/profile','PUT',{body:profileText,version:profile.version});setProfile(p);setProfileText(p.body);clearContext();memoryDialog.current?.close();setNotice('个人记忆已保存。助手下次发送时采用；旧调用和研究任务保留原快照。');}catch(e){setError((e as Error).message);memoryDialog.current?.close();}finally{setBusy(false);}}}>保存我的记忆</button><button disabled={busy} onClick={async()=>{try{const p=await request<AssetProfile>('asset-workspace/profile');setProfile(p);setProfileText(p.body);}catch(e){setError((e as Error).message);memoryDialog.current?.close();}}}>重新读取当前版本</button></div><details onToggle={e=>{if(e.currentTarget.open)void request<{items:typeof memoryHistory}>('asset-workspace/profile/history').then(r=>setMemoryHistory(r.items)).catch(e=>setError(e.message));}}><summary>查看最近20个记忆版本</summary>{memoryHistory.map(m=><div key={m.version}><small>v{m.version} · {new Date(m.updated_at).toLocaleString()}</small><p>{m.body||'已清空'}</p><button onClick={()=>setProfileText(m.body)}>以此版本为草稿</button></div>)}</details></dialog>
  </div>;
}
