import {useRef,useState} from 'react';
import {assetRequest,type AssetRef} from '../api/assetWorkspace';
import {businessRequest} from '../api/businessResearch';
import {intentId,finishIntent,type ResourceSpace} from './ResourceWorkspace';

export function PublishAsset({assets}:{assets:{title:string;ref:AssetRef}[]}){
  const dialog=useRef<HTMLDialogElement>(null);
  const [opened,setOpened]=useState(false);
  const [spaces,setSpaces]=useState<ResourceSpace[]>([]),[space,setSpace]=useState(''),[asset,setAsset]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState('');
  async function open(){setOpened(true);dialog.current?.showModal();setError('');setResult('');setConfirmed(false);setBusy(true);try{const c=await businessRequest<{resource_spaces?:boolean}>('config');if(!c.resource_spaces)throw new Error('当前部署尚未启用组织空间；现有项目资料继续保持原权限。');const v=await businessRequest<{spaces:ResourceSpace[]}>('workspaces');setSpaces(v.spaces.filter(s=>s.can_manage));setSpace('');setAsset('');}catch(e){setSpaces([]);setError((e as Error).message);}finally{setBusy(false);}}
  async function publish(){const selected=assets.find(a=>a.ref.version_id===asset);if(!selected||!space)return;setBusy(true);setError('');try{const body={space_id:space,ref:selected.ref},id=intentId('publish',body);await assetRequest('asset-workspace/spaces/publish','POST',{...body,id});finishIntent('publish');setResult(`/workspace/assets?view=all-resources&space=${space}&resource=${id}`);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <><button type="button" disabled={!assets.length} onClick={()=>void open()}>发布到组织空间</button><dialog className="pw-dialog" ref={dialog} aria-label="发布资料到组织空间" onClose={()=>setOpened(false)}>{opened&&<><h2>发布固定版本</h2><p>将所选版本保存为归组织管理的独立副本。原文件后续修改或撤销不会自动影响此发布；空间管理员可单独撤销。</p>{error&&<p role="alert">{error}</p>}{result?<p role="status">发布已保存。<a href={result}>打开空间中的资料</a></p>:<form className="pw-settings" onSubmit={e=>{e.preventDefault();void publish();}}><label>本页资料<select required value={asset} onChange={e=>setAsset(e.target.value)}><option value="">选择要发布的版本</option>{assets.filter(a=>a.ref.kind==='document').map(a=><option value={a.ref.version_id} key={a.ref.version_id}>{a.title}</option>)}</select></label><label>目标空间<select required value={space} onChange={e=>setSpace(e.target.value)}><option value="">选择目标空间</option>{spaces.map(s=><option value={s.id} key={s.id}>{s.organization_name} / {s.name}{s.kind==='personal'?'（默认仅本人可见）':'（授权团队成员可见）'}</option>)}</select></label><label className="rw-publish-confirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>我确认将此版本发布到所选空间，并按该空间权限提供阅读。</span></label><button className="pw-primary" disabled={busy||!asset||!space||!confirmed}>确认发布此版本</button></form>}<button type="button" disabled={busy} onClick={()=>dialog.current?.close()}>关闭</button></>}</dialog></>;
}
