import {useEffect,useState,type ReactNode} from 'react';
import {useSearchParams} from 'react-router';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import {businessRequest} from '../api/businessResearch';
import {assetRequest,type AssetVersion,type SourceCapture} from '../api/assetWorkspace';
import {ProjectNavigation} from './ProjectNavigation';
import {useWorkspaceProjects} from './workspaceProjects';
import {CapturedFinancialTable} from './SourceCapturePanel';
import {browserOwner} from './IdentityBoundary';

export type ResourceSpace={id:string;name:string;organization_id:string;organization_name:string;kind:'personal'|'team';can_manage:boolean;organization_admin:boolean};
type Organization={id:string;name:string;role:string};
type Member={subject:string;display_name:string;role:string;active?:boolean};
const types=[['all-resources','全部'],['files','文件资料'],['library','知识库'],['financial-data','数据库']] as const;
const resourceType=(view:string)=>view==='files'?'files':view==='library'?'knowledge':view==='financial-data'?'database':'';
export function intentId(operation:string,body:unknown){
  const key=`finsight.space.intent:${browserOwner}:${operation}`,encoded=JSON.stringify(body);
  let prior:{encoded:string;id:string}|null=null;try{prior=JSON.parse(sessionStorage.getItem(key)||'null');}catch{/* Unreadable local intent creates no server action. */}
  if(prior?.encoded===encoded)return prior.id;
  const id=crypto.randomUUID();sessionStorage.setItem(key,JSON.stringify({encoded,id}));return id;
}
export function finishIntent(operation:string){sessionStorage.removeItem(`finsight.space.intent:${browserOwner}:${operation}`);}

export default function ResourceWorkspace({children}:{children:ReactNode}){
  const projects=useWorkspaceProjects(),[params,setParams]=useSearchParams();
  const view=params.get('view')||(params.has('project')?'project':'files'),spaceId=params.get('space')||'legacy';
  const [spaces,setSpaces]=useState<ResourceSpace[]>([]),[orgs,setOrgs]=useState<Organization[]>([]),[enabled,setEnabled]=useState(false),[loaded,setLoaded]=useState(false),[error,setError]=useState('');
  async function reload(){const v=await businessRequest<{spaces:ResourceSpace[];organizations:Organization[]}>('workspaces');setSpaces(v.spaces);setOrgs(v.organizations);}
  useEffect(()=>{let alive=true;businessRequest<{resource_spaces?:boolean}>('config').then(async c=>{if(!alive)return;setEnabled(!!c.resource_spaces);if(c.resource_spaces){const v=await businessRequest<{spaces:ResourceSpace[];organizations:Organization[]}>('workspaces');if(alive){setSpaces(v.spaces);setOrgs(v.organizations);}}}).catch(e=>alive&&setError(e.message)).finally(()=>alive&&setLoaded(true));return()=>{alive=false;};},[]);
  const selected=spaces.find(s=>s.id===spaceId);
  function selectSpace(id:string){setParams(p=>{p.set('space',id);['resource','scope','project','asset','q','offset','return_project'].forEach(k=>p.delete(k));return p;});}
  function selectType(value:string){setParams(p=>{p.set('view',value);['resource','asset','project','source','metric','offset'].forEach(k=>p.delete(k));return p;});}
  return <div className="fs-workspace pw-shell" data-theme={localStorage.getItem('finsight.theme')||'system'}><ProjectNavigation projects={projects.index.projects} global="assets"/><main className="pw-main"><header className="pw-top"><a href="/workspace/projects">所有项目</a><span>/</span><span>资料库</span>{selected&&<><span>/</span><span>{selected.organization_name} · {selected.name}</span></>}{params.get('return_thread')&&<a href={`/workspace/session?thread=${encodeURIComponent(params.get('return_thread')!)}&view=graph`}>返回研究</a>}</header><div className="pw-content">
    <header className="pw-title"><div><h1>资料库</h1><p>{selected?`${selected.organization_name} · ${selected.kind==='personal'?'组织内个人工作区，默认本人可见':'团队共享空间'}`:'统一查阅文件资料、知识库与数据库。'}</p></div></header>
    <div className="pw-toolbar"><label>所属空间 <select aria-label="所属空间" value={spaceId} onChange={e=>selectSpace(e.target.value)}><option value="legacy">现有资料</option>{spaceId!=='legacy'&&!selected&&<option value={spaceId} disabled>空间不可访问</option>}{spaces.map(s=><option key={s.id} value={s.id}>{s.organization_name} / {s.name}{s.kind==='personal'?'（个人区）':''}</option>)}</select></label>{enabled&&<span className="pw-muted">组织资料归组织管理；个人区默认不对同事开放。</span>}</div>
    <nav className="pw-toolbar rw-types" aria-label="资料类型导航">{types.map(([key,label])=><button key={key} aria-current={view===key?'page':undefined} onClick={()=>selectType(key)}>{label}</button>)}{spaceId==='legacy'&&<button aria-current={['companies','institutions','policy'].includes(view)?'page':undefined} onClick={()=>selectType('companies')}>公司与机构</button>}</nav>
    {error&&<p role="alert">{error}</p>}
    {enabled&&<SpaceManagement spaces={spaces} organizations={orgs} selected={selected} onReload={reload} onSelect={selectSpace}/>}
    {spaceId==='legacy'?(view==='all-resources'?<div className="pw-grid">{types.slice(1).map(([key,label])=><section className="pw-card" key={key}><h2>{label}</h2><p>{key==='files'?'按项目整理的文件、笔记和成果。':key==='library'?'当前部署可用的公开原文和知识目录。':'当前部署可用的公开财务和指标数据。'}</p><button onClick={()=>selectType(key)}>查看{label}</button></section>)}</div>:children):!loaded?<p role="status">正在读取空间…</p>:selected?<SpaceResources space={selected} type={resourceType(view)}/>:<p role="alert">此空间不可访问，请选择有权限的空间。</p>}
    {spaceId==='legacy'&&<p className="pw-muted">现有项目文件保持原个人权限；这里的知识库与数据库为部署级资料。组织空间中的发布版本单独管理权限。</p>}
  </div></main></div>;
}

function SpaceManagement({organizations,selected,onReload,onSelect}:{spaces:ResourceSpace[];organizations:Organization[];selected?:ResourceSpace;onReload:()=>Promise<void>;onSelect:(id:string)=>void}){
  const [name,setName]=useState(''),[display,setDisplay]=useState(''),[invite,setInvite]=useState(''),[createdInvite,setCreatedInvite]=useState(''),[team,setTeam]=useState('');
  const [org,setOrg]=useState(''),[members,setMembers]=useState<Member[]>([]),[spaceMembers,setSpaceMembers]=useState<Member[]>([]),[subject,setSubject]=useState(''),[role,setRole]=useState('reader'),[revision,refresh]=useState(0);
  const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
  const activeOrg=selected?.organization_id||org||organizations[0]?.id||'',admin=organizations.find(o=>o.id===activeOrg)?.role==='admin';
  useEffect(()=>{let alive=true;setMembers([]);setSpaceMembers([]);setSubject('');if(activeOrg)businessRequest<Member[]>(`workspaces/organizations/${activeOrg}/members`).then(v=>alive&&setMembers(v)).catch(e=>alive&&setError(e.message));if(selected?.can_manage&&selected.kind==='team')businessRequest<Member[]>(`workspaces/spaces/${selected.id}/members`).then(v=>alive&&setSpaceMembers(v)).catch(e=>alive&&setError(e.message));return()=>{alive=false;};},[activeOrg,selected?.id,selected?.can_manage,revision]);
  useEffect(()=>setCreatedInvite(''),[activeOrg]);
  async function action(fn:()=>Promise<void>){setBusy(true);setMessage('');setError('');try{await fn();await onReload();refresh(n=>n+1);setMessage('已保存。');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <details className="pw-panel rw-management"><summary>空间与成员管理</summary><div className="rw-management-body">{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
    <form className="pw-toolbar" onSubmit={e=>{e.preventDefault();void action(async()=>{const body={name,display_name:display},id=intentId('create-organization',body);const v=await businessRequest<{spaces:ResourceSpace[]}>('workspaces/organizations','POST',{...body,id});finishIntent('create-organization');setName('');const s=v.spaces.find(s=>s.organization_id===id&&s.kind==='personal');if(s)onSelect(s.id);});}}><input required maxLength={120} aria-label="组织名称" placeholder="新组织名称" value={name} onChange={e=>setName(e.target.value)}/><input required maxLength={80} aria-label="我的成员名称" placeholder="你在组织内的显示名称" value={display} onChange={e=>setDisplay(e.target.value)}/><button disabled={busy}>创建组织</button></form>
    <form className="pw-toolbar" onSubmit={e=>{e.preventDefault();void action(async()=>{await businessRequest('workspaces/join','POST',{token:invite.trim(),display_name:display});setInvite('');});}}><input required aria-label="组织邀请码" placeholder="粘贴组织邀请码" value={invite} onChange={e=>setInvite(e.target.value)}/><button disabled={busy||!display.trim()}>加入组织</button></form>
    {organizations.length>0&&<div className="pw-toolbar"><label>管理组织 <select aria-label="管理组织" value={activeOrg} disabled={!!selected} onChange={e=>setOrg(e.target.value)}>{organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>{admin&&<button disabled={busy} onClick={()=>void action(async()=>{const token=intentId('invite',activeOrg);await businessRequest(`workspaces/organizations/${activeOrg}/invites`,'POST',{token});setCreatedInvite(token);finishIntent('invite');})}>生成成员邀请码</button>}</div>}
    {createdInvite&&<p>邀请码（7天内有效，仅一人可用）：<code>{createdInvite}</code></p>}
    {admin&&<form className="pw-toolbar" onSubmit={e=>{e.preventDefault();void action(async()=>{const body={organization_id:activeOrg,name:team};const s=await businessRequest<ResourceSpace>('workspaces/spaces','POST',{...body,id:intentId('create-team',body)});finishIntent('create-team');setTeam('');onSelect(s.id);});}}><input required maxLength={120} aria-label="团队空间名称" placeholder="新团队空间名称" value={team} onChange={e=>setTeam(e.target.value)}/><button disabled={busy}>创建团队空间</button></form>}
    {selected?.kind==='team'&&selected.can_manage&&<><h3>团队空间成员</h3><p className="pw-muted">阅读成员可以读取发布资料；空间管理员可以发布、撤销和管理成员。组织管理员可管理团队空间。</p>{spaceMembers.map(m=><p key={m.subject}>{m.display_name} · {m.role==='manager'?'空间管理员':'阅读成员'}</p>)}<form className="pw-toolbar" onSubmit={e=>{e.preventDefault();void action(async()=>{await businessRequest(`workspaces/spaces/${selected.id}/members`,'POST',{subject,role});});}}><select required aria-label="选择组织成员" value={subject} onChange={e=>setSubject(e.target.value)}><option value="">选择成员</option>{members.filter(m=>m.active).map(m=><option value={m.subject} key={m.subject}>{m.display_name}</option>)}</select><select aria-label="空间成员权限" value={role} onChange={e=>setRole(e.target.value)}><option value="reader">阅读成员</option><option value="manager">空间管理员</option><option value="remove">移出空间</option></select><button disabled={busy||!subject}>保存成员权限</button></form></>}
    {admin&&members.some(m=>m.active&&m.role!=='admin')&&<><h3>组织成员</h3>{members.filter(m=>m.active&&m.role!=='admin').map(m=><p key={m.subject}>{m.display_name} <button disabled={busy} onClick={()=>{if(window.confirm(`将 ${m.display_name} 移出组织？其组织访问权限将失效，已发布资料会保留。`))void action(async()=>{await businessRequest(`workspaces/organizations/${activeOrg}/remove-member`,'POST',{subject:m.subject});});}}>移出组织</button></p>)}<p className="pw-muted">移出后不能访问组织空间，已发布资料保留；管理员交接和个人区接管后续开放。</p></>}
  </div></details>;
}

function SpaceResources({space,type}:{space:ResourceSpace;type:string}){
  const [params,setParams]=useSearchParams(),id=params.get('resource')||'',query=params.get('q')||'',offset=Math.max(0,Number(params.get('offset'))||0);
  const [rows,setRows]=useState<{id:string;title:string;resource_type:string;revision:number}[]>([]),[next,setNext]=useState<number|null>(null),[search,setSearch]=useState(query),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,refresh]=useState(0);
  const [reading,setReading]=useState<{version:AssetVersion;text:string;truncated:boolean;needs_vision?:boolean;capture?:SourceCapture;permission_revision:number}|null>(null);
  useEffect(()=>setSearch(query),[query]);
  useEffect(()=>{let alive=true;setError('');setReading(null);setRows([]);setNext(null);setBusy(true);const req=id?assetRequest<any>(`asset-workspace/spaces/resources/${id}`):businessRequest<any>(`workspaces/spaces/${space.id}/resources?${new URLSearchParams({type,query,offset:String(offset)})}`);req.then(v=>{if(alive){if(id){if(v.publication?.space_id!==space.id)throw new Error('此资料不属于当前空间，请返回列表重新选择。');setReading(v);}else{setRows(v.items);setNext(v.next_offset);}}}).catch(e=>alive&&setError(e.message)).finally(()=>alive&&setBusy(false));return()=>{alive=false;};},[space.id,id,type,query,offset,revision]);
  return <section>{error&&<p role="alert">{error} <button onClick={()=>refresh(n=>n+1)}>重新读取</button></p>}{id?<><button onClick={()=>setParams(p=>{p.delete('resource');return p;})}>返回空间资料</button>{reading&&<article className="pw-card rw-reading"><h2>{reading.version.title}</h2><p>发布的固定版本 · 只读</p>{reading.capture?.rows&&<CapturedFinancialTable rows={reading.capture.rows}/>}<ReactMarkdown remarkPlugins={[remarkGfm]}>{reading.text}</ReactMarkdown>{reading.capture?.note&&<aside><h3>发布时的批注（非来源事实）</h3><p>{reading.capture.note}</p></aside>}{reading.truncated&&<p>正文超过当前阅读长度，页面只展示部分内容。</p>}{reading.needs_vision&&<p>该文件需要图像阅读，当前文本视图不能完整呈现。</p>}{space.can_manage&&<button onClick={async()=>{if(!window.confirm('撤销此发布后，空间成员将无法继续读取此版本。原项目资料保留。'))return;setError('');try{await businessRequest(`workspaces/resources/${id}/revoke`,'POST',{revision:reading.permission_revision});setParams(p=>{p.delete('resource');return p;});refresh(n=>n+1);}catch(e){setError((e as Error).message);}}}>撤销此发布</button>}</article>}</>:<><form className="pw-toolbar" onSubmit={e=>{e.preventDefault();setParams(p=>{p.set('q',search);p.delete('offset');return p;});}}><input maxLength={200} aria-label="搜索空间资料" placeholder="搜索当前空间的资料" value={search} onChange={e=>setSearch(e.target.value)}/><button>搜索</button></form><div className="pw-panel">{rows.map(r=><button className="pw-row rw-resource-row" key={r.id} onClick={()=>setParams(p=>{p.set('resource',r.id);return p;})}><span><strong>{r.title}</strong><small>{{files:'文件资料',knowledge:'知识库选取',database:'数据库快照'}[r.resource_type]} · 发布版本</small></span><span>阅读 →</span></button>)}{!busy&&!error&&!rows.length&&<p className="pw-empty">当前范围内尚无发布资料。可从项目资料选择固定版本，发布到此空间。</p>}</div><div className="pw-toolbar"><button disabled={!offset||busy} onClick={()=>setParams(p=>{p.set('offset',String(Math.max(0,offset-30)));return p;})}>上一页</button><button disabled={next===null||busy} onClick={()=>setParams(p=>{p.set('offset',String(next));return p;})}>下一页</button></div><p className="pw-muted">文件、知识库选取和财务数据快照按发布时版本阅读。原文件后续修改不会自动替换；本批尚未开放团队资料交给 Agent 或实时数据库查询。</p></>}{busy&&<p role="status">正在读取资料…</p>}</section>;
}
