import { useMemo, useState } from "react";
import { ArrowRight, CheckCircle2, CircleDashed, FileText, GitBranch, LoaderCircle, MessageSquarePlus, Radio, Square, TriangleAlert } from "lucide-react";
import { sessionsApi, type Event, type Session } from "../api/reportSessions";

const statusName = (status: string) => ({running:"执行中", pending:"等待执行", success:"运行完成，待审阅", interrupted:"已到达等待点 / 已停止", error:"执行失败", submitted:"已交底稿", planned:"等待执行", ready:"等待执行", specialist_submission_accepted:"底稿已提交"} as Record<string,string>)[status] || status;
const nodeName = (actor: string) => ({writer:"报告修订", report_verifier:"报告独立复核", responsibility_router:"问题责任分派", synthesis:"综合研究判断", research_verifier:"研究判断复核", lead:"研究负责人", counter:"反证审查", human_guidance:"用户补充意见"} as Record<string,string>)[actor] || actor;
const eventStatus = (status?: string) => ({success:"调用成功", error:"调用失败", submitted:"结果已提交", running:"调用中"} as Record<string,string>)[status || ""] || status || "结果已记录";
const actorStatus = (e: Event, live: boolean) => e.event === "applied" ? "已读取" : e.kind === "stage" && e.event === "outcome" ? "阶段结果已提交" : e.status === "error" ? "执行失败" : live ? "处理中" : "执行记录已保存";

/** Views of SDK/public audit events. No synthetic progress or browser-owned execution state. */
export function RunWorkspace({ session, events, connected, refresh, onReport }: { session: Session; events: Event[]; connected: boolean; refresh:()=>Promise<void>; onReport:()=>void }) {
  const [chosenRun, setChosenRun] = useState(""); const [selection,setSelection] = useState<{kind:"task"|"actor";id:string}|null>(null);
  const [message,setMessage]=useState(""); const [sending,setSending]=useState(false); const [notice,setNotice]=useState("");
  const run=session.runs?.find(r=>r.run_id===chosenRun) || session.runs?.[0];
  const live=run?.status==="running" || run?.status==="pending";
  const visible=useMemo(()=>events.filter(e=>!run || e.run_id===run.run_id),[events,run?.run_id]);
  const stages=useMemo(()=>[...new Set(visible.map(e=>e.actor).filter(Boolean))].map(actor=>({actor,latest:visible.filter(e=>e.actor===actor).at(-1)!})),[visible]);
  const tasks=useMemo(()=>{const map=new Map<string,{id:string;title:string;status:string;deps:string[]}>();
    for(const e of visible) if(e.kind==="task" && e.task_id) map.set(e.task_id,{id:e.task_id,title:e.objective||e.task_id,status:e.status||e.event,deps:e.dependency_ids||[]});
    // Saved task summaries describe the initial research, not every later revision run.
    if(!run?.human_action && run===session.runs?.[0]) for(const t of session.research_tasks||[]) map.set(t.task_id,{id:t.task_id,title:t.objective,status:t.status,deps:t.dependency_ids});
    return [...map.values()];},[visible,run,session.research_tasks]);
  const activity=selection ? visible.filter(e=>selection.kind==="task" ? e.task_id===selection.id : e.actor===selection.id) : visible;
  const outcome = (e:Event) => e.kind==="tool" ? `${e.tool || "工具"} · ${e.event === "outcome" ? eventStatus(e.status) : "开始调用"}` : e.kind==="model" ? `${e.event === "outcome" ? "模型结果" : "模型调用"} · ${e.status ? eventStatus(e.status) : "已发起"}` : e.objective || (e.event === "started" ? "开始处理" : e.event === "outcome" ? "已提交阶段结果" : e.event === "handoff" ? `交接至 ${nodeName(e.status || "下阶段")}` : e.event);
  return <section className="fs-run-workspace"><div className="fs-run-heading"><div><span className="fs-kicker"><Radio size={15}/> RESEARCH IN MOTION</span><h2>研究现场</h2><p>{run ? statusName(run.status) : "尚无运行"} · {connected ? "实时事件已连接" : "显示已保存记录"}</p></div><button onClick={refresh}>刷新状态</button>{session.report && <button onClick={onReport}><FileText size={15}/>阅读当前报告</button>}</div>
    <div className="fs-run-selector"><label htmlFor="fs-run-picker">运行记录</label><select id="fs-run-picker" value={run?.run_id || ""} onChange={e=>{setChosenRun(e.target.value);setSelection(null);}}>{session.runs?.map(r=><option key={r.run_id} value={r.run_id}>{r.created_at ? new Date(r.created_at).toLocaleString("zh-CN") : r.run_id} · {r.human_action || "研究"} · {statusName(r.status)}</option>)}</select></div>
    {run?.revision_target && <div className="fs-run-target"><GitBranch size={16}/><span>修订目标 <strong>{run.revision_target.citation_id}</strong> · 基线 v{run.revision_target.base_version} → 当前 v{session.report_version}。目标来自已保存引用；实际调用以事件为准。</span></div>}
    <div className="fs-run-split"><div className="fs-run-map"><div className="fs-list-heading"><h3>{tasks.length ? "正在推进的话题" : "本次实际执行阶段"}</h3><button onClick={()=>setSelection(null)}>查看全部活动</button></div><p className="fs-run-note">{tasks.length ? "任务按运行时实际分工出现；点击查看带相同任务标识的活动。" : "阶段在收到真实事件后出现；先后记录不等于完整的依赖图。"}</p>
      {tasks.length ? <div className="fs-run-topics">{tasks.map(t=><button className="fs-run-node" key={t.id} aria-pressed={selection?.id===t.id} onClick={()=>setSelection({kind:"task",id:t.id})}><span><GitBranch size={17}/>{statusName(t.status)}</span><h3>{t.title}</h3><small>{t.id}</small><footer>{t.deps.length ? `等待 / 依赖：${t.deps.join("、")}` : "无前置任务依赖"}<ArrowRight size={15}/></footer></button>)}</div> : <div className="fs-stage-chain">{stages.map(({actor,latest})=><button className="fs-run-node" key={actor} aria-pressed={selection?.id===actor} onClick={()=>setSelection({kind:"actor",id:actor})}><span>{latest.status==="error" ? <TriangleAlert size={17}/> : latest.event==="applied" || (latest.kind==="stage" && latest.event==="outcome") ? <CheckCircle2 size={17}/> : live ? <LoaderCircle size={17} className="rs-spin"/> : <CircleDashed size={17}/>} {actorStatus(latest, !!live)}</span><h3>{nodeName(actor)}</h3><small>{actor}</small><footer>查看该阶段活动<ArrowRight size={15}/></footer></button>)}</div>}
      {!tasks.length && !stages.length && <div className="fs-empty"><CircleDashed size={28}/><h3>{live ? "等待首条实际事件" : "这次运行没有可展示的阶段事件"}</h3><p>不会据耗时生成假进度。历史缺失事件不代表执行未发生。</p></div>}
      <div className="fs-run-usage"><h3>本次运行用量</h3><div><strong>{run?.cost_estimate ? `¥${run.cost_estimate.known_cny.toFixed(4)}` : "未记录"}</strong><span>已知费用</span><strong>{run?.usage?.total_tokens?.toLocaleString() ?? "未记录"}</strong><span>已报告 tokens</span></div><p>未计价 / 待确认请求：{run?.cost_estimate?.unknown_or_pending_requests ?? "未记录"}。费用按已取得用量汇总，未知不计作零。</p></div>
      <div className="fs-run-participation"><h3><MessageSquarePlus size={17}/>参与这次研究</h3><textarea aria-label="运行中补充意见" value={message} onChange={e=>setMessage(e.target.value)} placeholder="补充需要核实的范围、来源或假设，后续阶段读取…" disabled={!live || !session.question || sending}/><div><button disabled={!live || !session.question || !message.trim() || sending} onClick={async()=>{setSending(true);try{await sessionsApi.guidance(session.thread_id,message);setNotice("意见已保存，等待后续阶段读取；以实际应用事件为准。");setMessage("");await refresh();}catch(e){setNotice((e as Error).message);}finally{setSending(false);}}}>补充意见 · 下阶段读取</button><button disabled={!live || sending} onClick={async()=>{if(!run)return;setSending(true);try{await sessionsApi.cancel(session.thread_id,run.run_id);setNotice("已请求停止，保留已产生结果。");await refresh();}catch(e){setNotice((e as Error).message);}finally{setSending(false);}}}><Square size={12}/>停止这次运行</button></div>{notice && <p role="status">{notice}</p>}</div>
    </div><aside className="fs-activity-stream" aria-label="公开研究活动"><header><strong>{selection ? selection.kind==="actor" ? nodeName(selection.id) : "所选话题" : "全部研究活动"}</strong><span>{activity.length} 条已收到事件</span></header><div className="fs-activity-items">{activity.map((e,i)=><article key={`${e.run_id}:${e.call_id}:${e.recorded_at}:${i}`}><small>{nodeName(e.actor)} · {e.recorded_at ? new Date(e.recorded_at).toLocaleTimeString("zh-CN") : "时间未记录"}</small><p>{outcome(e)}</p>{e.total_tokens!==undefined && <span>{e.total_tokens.toLocaleString()} tokens</span>}{e.tool && <code>{e.tool}</code>}<details><summary>事件标识</summary><code>{e.run_id}<br/>{e.task_id || e.call_id || e.actor}</code></details></article>)}{!activity.length && <p>没有带此关联标识的公开事件。可切回全部活动查看，不推测未记录的对应关系。</p>}</div><footer>仅展示公开进展和已记录调用。新的事件追加在末尾，保留你的当前阅读位置。</footer></aside></div>
  </section>;
}
