"""Bounded public-text Qwen connectivity qualification; no index or model promotion."""
from __future__ import annotations

import argparse
from dataclasses import asdict
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import os
import time

from retrieval.qwen_api import QwenRetrieval


def run(directory: Path):
    directory.mkdir(parents=True, exist_ok=False)
    texts = ["Revenue and operating cash flow are different financial measures.",
             "Operating cash flow records cash generated or used by operating activities.",
             "HTTP caching can reuse a previously stored response."]
    query = "Which measure describes cash generated by operations?"
    basis = {"purpose": "Confirm authorized Qwen embedding/rerank protocol and reported usage",
        "input_scale": "Three public generic sentences plus one query; no private data",
        "required_outputs": "Four 1024-dimensional vectors and three ranked document indices",
        "schema_burden": "Provider native embedding/rerank output, no generation",
        "materiality_quality_risk": "Connectivity only; no retrieval-quality or financial acceptance claim",
        "comparable_run_evidence": "Existing local Qwen baseline retained; no index mutation",
        "reasoning_profile": "Embedding/rerank inference only",
        "stop_truncation_behavior": "One call per endpoint, no automatic retry; stop on error",
        "maximum_calls": 2, "input_sha256": hashlib.sha256(json.dumps([query, texts]).encode()).hexdigest()}
    (directory / "basis.json").write_text(json.dumps(basis, indent=2), encoding="utf-8")
    key = os.environ.get("QWEN_API_KEY")
    if not key:
        raise ValueError("QWEN_API_KEY_missing")
    api = QwenRetrieval(key)
    try:
        for name, call in (("embedding", lambda: api.embed([query, *texts])),
                           ("rerank", lambda: api.rerank(query, texts))):
            started = time.perf_counter()
            (directory / f"{name}-started.json").write_text(json.dumps({
                "at": datetime.now(timezone.utc).isoformat(), "usage": "pending"}), encoding="utf-8")
            try:
                result = call()
            except Exception as exc:
                failure = {"type": type(exc).__name__, "status": getattr(exc, "status_code", None),
                           "code": getattr(exc, "code", None), "usage": "unknown",
                           "elapsed_seconds": time.perf_counter() - started}
                (directory / f"{name}-failure.json").write_text(json.dumps(failure, indent=2), encoding="utf-8")
                print(json.dumps({"operation": name, "failure": failure}))
                return 1
            payload = {**asdict(result), "elapsed_seconds": time.perf_counter() - started}
            (directory / f"{name}.json").write_text(json.dumps(payload), encoding="utf-8")
            print(json.dumps({"operation": name, "usage": result.usage,
                              "count": len(result.values), "elapsed_seconds": payload["elapsed_seconds"]}))
    finally:
        api.close()
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    raise SystemExit(run(args.output))
