import {test,expect} from 'playwright/test';

for(const width of [1440,390])test(`资产阅读修订记忆与双向交接 ${width}`,async({page,browser},info)=>{
  test.skip(!process.env.FIN_ASSET_WORKSPACE_FIXTURE,'Requires isolated asset fixture');
  await page.setViewportSize({width,height:1000});
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/workspace/assets');
  await expect(page.getByLabel('资产项目')).toHaveValue('00000000-0000-4000-8000-000000000053');
  await page.getByRole('button',{name:/资本开支与现金创造/}).click();
  await expect(page.getByLabel('资产正文')).toContainText('从投资规模');
  await page.screenshot({path:info.outputPath(`assets-${width}.png`),fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
  await page.getByRole('button',{name:'我的记忆',exact:true}).click();
  await page.getByLabel('个人长期记忆').fill(`关注现金创造能力，保留期间与单位。验收 ${width}`);
  await page.getByRole('button',{name:'保存我的记忆',exact:true}).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await expect(page.getByText('个人记忆已保存。下次准备任务会绑定这一版。')).toBeVisible();
  const project=new URL(page.url()).searchParams.get('project');
  await page.getByRole('button',{name:'新建笔记',exact:true}).click();
  await page.getByLabel('资产标题').fill(`我的研究假设 ${width}`);
  await page.getByLabel('资产内容').fill('# 初始判断\n\n这是用户的待核验假设，不能当作权威事实。');
  await page.getByRole('button',{name:'保存版本',exact:true}).click();
  await expect(page.getByLabel('资产正文')).toContainText('初始判断');
  const second=await browser.newContext({viewport:{width,height:1000}});
  try{
    const other=await second.newPage();await other.goto(`/workspace/assets?project=${project}`);
    await other.getByRole('button',{name:new RegExp(`我的研究假设 ${width}`)}).click();
    await expect(other.getByLabel('资产正文')).toContainText('初始判断');
    await other.getByRole('button',{name:'编辑',exact:true}).click();
    await other.getByLabel('资产内容').fill('# 另一个窗口\n\n这次修改不应覆盖已更新的版本。');
    await page.getByRole('button',{name:'编辑',exact:true}).click();
    await page.getByLabel('资产内容').fill('# 新判断\n\n保留初始假设，但需要额外来源验证。');
    await page.getByRole('button',{name:'保存版本',exact:true}).click();
    await expect(page.getByLabel('资产正文')).toContainText('新判断');
    await other.getByRole('button',{name:'保存版本',exact:true}).click();
    await expect(other.getByRole('alert')).toContainText('已有后续版本');
    await expect(other.getByLabel('资产内容')).toHaveValue('# 另一个窗口\n\n这次修改不应覆盖已更新的版本。');
  }finally{await second.close();}
  await page.getByRole('button',{name:'版本',exact:true}).click();
  await page.getByRole('button',{name:/^v1 ·/}).click();
  await expect(page.getByLabel('资产正文')).toContainText('初始判断');
  const question=`请先读取这份历史资料，指出仍待核验的假设和所需原始来源。${width}`;
  await page.getByLabel('资产问题').fill(question);
  await page.getByRole('button',{name:'保存问题',exact:true}).click();
  await expect(page.getByText('问题与所选资料版本已保存，尚未调用模型。')).toBeVisible();
  const savedUrl=page.url();
  await page.reload();
  await expect(page.getByLabel('资产问题')).toHaveValue(question);
  await expect(page.getByLabel('资产正文')).toContainText('初始判断');
  await page.getByRole('button',{name:'交给研究团队',exact:true}).click();
  await expect(page.getByLabel('资产交接信息')).toContainText('已固定资料版本');
  const tid=new URL(page.url()).searchParams.get('thread');
  const draft=await(await page.request.get(`/api/v1/research-sessions/${tid}`)).json();
  expect(draft.question).toBe(question);expect(draft.runs).toEqual([]);
  expect(draft.attachments[0].project_origin.document_id).toBe(draft.asset_context.refs[0].version_id);
  expect(draft.asset_context.memory.body).toContain(String(width));
  await page.screenshot({path:info.outputPath(`asset-research-${width}.png`),fullPage:true});
  await page.getByRole('link',{name:'返回资产与原问题 →'}).click();
  await expect(page.getByLabel('资产正文')).toContainText('初始判断');
  await expect(page.getByLabel('资产问题')).toHaveValue(question);
  await page.getByRole('button',{name:'准备助手对话',exact:true}).click();
  await expect(page.getByLabel('资产交接信息')).toContainText('已固定资料版本');
  await expect(page.getByRole('textbox',{name:'发送消息',exact:true})).toHaveValue(question);
  const conversation=await(await page.request.get(`/api/v1/conversations/${new URL(page.url()).searchParams.get('thread')}`)).json();
  expect(conversation.runs).toEqual([]);expect(conversation.asset_context.context_id).toBe(draft.asset_context.context_id);
  await page.screenshot({path:info.outputPath(`asset-assistant-${width}.png`),fullPage:true});
  await page.goto(savedUrl);await expect(page.getByLabel('资产正文')).toContainText('初始判断');
  expect(errors).toEqual([]);
});
