import {test,expect} from 'playwright/test';
import {randomUUID} from 'node:crypto';
import {writeFile} from 'node:fs/promises';

for(const width of [1440,390])test(`报告保存修改重查及任务版本绑定 ${width}`,async({page,browser},testInfo)=>{
  test.skip(!process.env.FIN_PROJECT_REPORT_SOURCE,'Explicit saved development source and native manual graph fixture');
  test.setTimeout(60000);
  const tid='00000000-0000-4000-8000-000000000015';
  const project=randomUUID(),name=`成果版本 ${width}`;
  const index=await (await page.request.get('/api/v1/projects')).json();
  expect((await page.request.put('/api/v1/projects',{headers:{'X-Workbench-Request':'1'},data:{...index,projects:[...index.projects,{id:project,name}]}})).status()).toBe(200);
  await page.setViewportSize({width,height:1000});
  await page.goto(`/workspace/session?thread=${tid}&view=report`);
  const state=await (await page.request.get(`/api/v1/research-sessions/${tid}`)).json();
  const initialVersion=state.report_version;
  const section=page.getByLabel('保存报告到项目',{exact:true});
  await section.getByLabel('保存报告的目标项目').selectOption(project);
  const firstResponse=page.waitForResponse(r=>r.url().endsWith(`/projects/${project}/reports`)&&r.request().method()==='POST');
  await section.getByRole('button',{name:`保存 v${initialVersion} 到项目`,exact:true}).click();
  const first=await (await firstResponse).json();
  await expect(section.getByRole('status')).toContainText('正文可查找');
  await page.getByRole('button',{name:'人工修改与确认',exact:true}).click();
  const dialog=page.getByRole('dialog',{name:'人工修改与确认'});
  const marker=`本轮复核标记${width}：只保留观察，撤回未证实归因。`;
  await dialog.getByLabel('人工修改报告正文').fill(state.report.narrative_markdown+'\n\n'+marker);
  await dialog.getByLabel('人工修改说明').fill(`项目接续资格 ${width}，保留原引用`);
  await dialog.getByRole('checkbox').check();
  await dialog.getByRole('button',{name:'保存修改并确认完成',exact:true}).click();
  await expect(dialog).not.toBeVisible();
  const version=initialVersion+1;
  await section.getByLabel('保存报告的目标项目').selectOption(project);
  const secondResponse=page.waitForResponse(r=>r.url().endsWith(`/projects/${project}/reports`)&&r.request().method()==='POST');
  await section.getByRole('button',{name:`保存 v${version} 到项目`,exact:true}).click();
  const second=await (await secondResponse).json();
  expect(second.document_id).not.toBe(first.document_id);
  expect(second.project_origin.research_origin.human_edit_count).toBe(version-1);
  const old=await page.request.get(`/api/v1/projects/${project}/documents/${encodeURIComponent(first.document_id)}/download`);
  expect(await old.text()).not.toContain(marker);
  const diff=await (await page.request.get(`/api/v1/research-sessions/${tid}/report-diff?before=${first.project_origin.research_origin.checkpoint_id}`)).json();
  expect(diff.diff).toContain('+'+marker);
  await writeFile(testInfo.outputPath('saved-versions.json'),JSON.stringify({first,second,diff},null,2));
  await section.scrollIntoViewIfNeeded();
  await page.screenshot({path:testInfo.outputPath(`save-report-${width}.png`),fullPage:true});
  expect(await section.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);
  await section.getByRole('button',{name:'打开已保存项目',exact:true}).click();
  await expect(page.getByRole('heading',{name,exact:true})).toBeVisible();
  await page.getByLabel('查找项目资料',{exact:true}).fill(`本轮复核标记${width}`);
  await page.getByRole('button',{name:'查找',exact:true}).click();
  await expect(page.locator('.fs-project-documents article')).toHaveCount(1);
  await page.getByRole('button',{name:'阅读已保存正文',exact:true}).click();
  await expect(page.getByLabel('项目资料正文')).toContainText(marker);
  await page.screenshot({path:testInfo.outputPath(`report-project-${width}.png`),fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
  const other=await browser.newContext({viewport:{width:390,height:950}});
  try{const phone=await other.newPage();await phone.goto(page.url());
    await expect(phone.locator('.fs-project-documents article')).toHaveCount(2);
    await expect(phone.locator('.fs-project-documents')).toContainText(`研究成果 v${version}`);
  }finally{await other.close();}
  await page.getByLabel(`选择资料 ${second.name}`,{exact:true}).check();
  await page.getByRole('button',{name:'用所选资料准备研究',exact:true}).click();
  await page.getByLabel('这次你想研究什么？',{exact:true}).fill('读取所选报告版本，区分用户判断和原始来源。');
  await page.getByRole('button',{name:'保存为资料准备草稿',exact:true}).click();
  await expect(page.getByText('资料准备任务已保存，尚未调用研究模型。',{exact:true})).toBeVisible();
  const newThread=new URL(page.url()).searchParams.get('thread');
  const selected=await (await page.request.get(`/api/v1/research-sessions/${newThread}`)).json();
  expect(selected.attachments[0].project_origin.research_origin.report_version).toBe(version);
  expect(selected.attachments[0].project_origin.research_origin.report_digest).toBe(second.project_origin.research_origin.report_digest);
  expect(selected.runs).toEqual([]);
  await writeFile(testInfo.outputPath('new-task-selection.json'),JSON.stringify(selected.attachments,null,2));
});
