import {test,expect} from "playwright/test";
test("live run projects actual actors, target and usage; selection does not invoke a model",async({page})=>{
  page.on("pageerror", error => { console.error(error.stack); });
  const id="00000000-0000-4000-8000-000000000031",runId="00000000-0000-4000-8000-000000000032";let writes=0;
  const session={thread_id:id,title:"Atlas · 局部修订",status:"interrupted",phase:"ready_for_human_review",report_version:2,report_digest:"a".repeat(64),report:{title:"报告",narrative_markdown:"## 判断\n\n待核实。[C1]",citations:{C1:{claim:{statement:"待核实"},sources:[]}}},runs:[{run_id:runId,status:"success",human_action:"revise",revision_target:{citation_id:"C1",base_version:1},cost_estimate:{known_cny:.03,unknown_or_pending_requests:1},usage:{total_tokens:120}}],model_events:[{run_id:runId,kind:"stage",actor:"writer",event:"started"},{run_id:runId,kind:"model",actor:"writer",event:"outcome",call_id:"call1",status:"success",total_tokens:80},{run_id:runId,kind:"stage",actor:"report_verifier",event:"started"},{run_id:runId,kind:"model",actor:"report_verifier",event:"outcome",call_id:"call2",status:"success",total_tokens:40}]};
  await page.route("**/api/v1/**",async route=>{if(route.request().method()!=="GET")writes++;const u=new URL(route.request().url());await route.fulfill({json:u.pathname.endsWith("research-sessions")?[session]:u.pathname.endsWith("research-session-config")?{fresh_research_enabled:false}:u.pathname.endsWith("report-versions")?{versions:[],next_cursor:null}:session});});
  await page.goto(`/workspace/session?thread=${id}&view=activity`);await expect(page.getByRole("heading",{name:"研究现场"})).toBeVisible();await expect(page.locator(".fs-run-target")).toContainText("C1");await expect(page.locator(".fs-run-target")).toContainText("基线 v1 → 当前 v2");await expect(page.locator(".fs-stage-chain .fs-run-node")).toHaveCount(2);
  await page.locator(".fs-stage-chain").getByRole("button",{name:/报告修订/}).click();await expect(page.locator(".fs-activity-items article")).toHaveCount(2);await expect(page.locator(".fs-activity-items")).not.toContainText("report_verifier");await page.getByRole("button",{name:"查看全部活动"}).click();await expect(page.locator(".fs-activity-items article")).toHaveCount(4);await expect(page.locator(".fs-run-usage")).toContainText("¥0.0300");await expect(page.locator(".fs-run-usage")).toContainText("待确认请求：1");await expect(page.getByRole("button",{name:"停止这次运行"})).toBeDisabled();expect(writes).toBe(0);
  await page.getByRole("button",{name:"回放已保存过程"}).click();await page.getByRole("button",{name:"暂停回放"}).click();await expect(page.getByRole("status")).toContainText("非实时执行");await expect(page.locator(".fs-activity-items article")).toHaveCount(1);
  await page.getByLabel("回放事件位置").fill("3");await expect(page.locator(".fs-activity-items article")).toHaveCount(3);
  await page.getByRole("button",{name:"退出回放"}).click();await expect(page.locator(".fs-activity-items article")).toHaveCount(4);expect(writes).toBe(0);
});
