import {test,expect} from 'playwright/test';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';

for(const width of [1440,390])test(`真实原文财务记录保存批注与双资产交接 ${width}`,async({page},info)=>{
  test.skip(!process.env.FIN_ASSET_LIBRARY_SETTINGS,'Requires an explicit local real-data snapshot');
  test.setTimeout(120000);
  const manifest=JSON.parse(readFileSync(resolve(process.env.FINSIGHT_LOCAL_STATE_ROOT!,'source-manifest.json'),'utf8'));
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.setViewportSize({width,height:1000});
  await page.addInitScript(()=>localStorage.setItem('finsight.theme','light'));
  await page.goto(`/workspace/assets?view=library&source=${encodeURIComponent(manifest.sample_document.document_id)}`);
  await expect(page.getByRole('dialog',{name:'公共资料阅读',exact:true})).toBeVisible({timeout:20000});
  await page.getByLabel('选择章节 1',{exact:true}).check();
  await page.getByRole('button',{name:'将所选章节加入项目',exact:true}).click();
  const saveDialog=page.getByRole('dialog',{name:'保存来源到项目',exact:true});
  await expect(page.getByLabel('来源目标项目')).not.toHaveValue('');
  await page.getByLabel('来源资产名称').fill(`微软披露原文 ${width}`);
  await page.getByLabel('来源批注').fill(`用户观察 ${width}：对照收入记录核验期间，尚未形成结论。`);
  await saveDialog.getByRole('button',{name:'保存到项目',exact:true}).click();
  await saveDialog.getByRole('link',{name:'打开已保存资产 →',exact:true}).click();
  await expect(page.getByLabel('固定来源与批注')).toContainText('固定原文 · 1 个章节');
  await expect(page.getByLabel('资产正文')).toContainText('Microsoft');
  await expect(page.getByRole('button',{name:'编辑',exact:true})).toBeDisabled();
  const sourceUrl=page.url();
  const project=new URL(sourceUrl).searchParams.get('project')!;
  await expect(page.getByRole('link',{name:'浏览当前来源',exact:true})).toHaveAttribute('href',new RegExp(encodeURIComponent(manifest.sample_document.document_id)));
  await page.screenshot({path:info.outputPath(`saved-library-${width}.png`),fullPage:true});

  await page.goto('/workspace/assets?view=financial-data&ticker=MSFT&metric=revenue');
  await expect(page.getByLabel('公司',{exact:true})).toHaveValue('MSFT');
  await expect(page.getByLabel('指标',{exact:true})).toHaveValue('revenue');
  await page.getByLabel('选择财务记录 1',{exact:true}).check();
  await page.getByLabel('选择财务记录 2',{exact:true}).check();
  await page.getByRole('button',{name:'保存所选记录',exact:true}).click();
  await page.getByLabel('来源资产名称').fill(`微软收入记录 ${width}`);
  await page.getByLabel('来源批注').fill(`原始批注 ${width}：不能把不同期间直接相加。`);
  await saveDialog.getByRole('button',{name:'保存到项目',exact:true}).click();
  await saveDialog.getByRole('link',{name:'打开已保存资产 →',exact:true}).click();
  await expect(page.getByLabel('固定来源与批注')).toContainText('固定财务记录 · 2 条');
  await expect(page.getByLabel('资产正文')).toContainText(manifest.sample_msft_revenue.value_decimal);
  const financialUrl=page.url();
  const version=new URL(financialUrl).searchParams.get('asset')!;
  await page.getByRole('button',{name:'围绕资料提问',exact:true}).click();
  await page.getByLabel(`用于研究 微软披露原文 ${width}.md`,{exact:true}).check();
  await page.getByLabel(`用于研究 微软收入记录 ${width}.md`,{exact:true}).check();
  await page.getByLabel('资产问题').fill(`核对所选披露章节与收入数据的期间，指出本次选择的覆盖限制。${width}`);
  await page.getByRole('button',{name:'交给研究团队',exact:true}).click();
  await expect(page.getByLabel('资产交接信息')).toContainText('已固定资料版本');
  const tid=new URL(page.url()).searchParams.get('thread')!;
  const task=await(await page.request.get(`/api/v1/research-sessions/${tid}`)).json();
  expect(task.attachments).toHaveLength(2);expect(task.runs).toEqual([]);
  expect(task.attachments.map((a:any)=>a.project_origin.asset_capture.kind).sort()).toEqual(['financial','library']);
  expect(task.asset_context.refs.some((r:any)=>r.version_id===version)).toBe(true);
  await page.getByRole('button',{name:'项目资料',exact:true}).click();
  await page.getByRole('complementary',{name:'项目资料侧栏'}).getByRole('button',{name:new RegExp(`微软收入记录 ${width}`)}).click();
  await expect(page.getByLabel('侧栏资料正文')).toContainText(`原始批注 ${width}`);
  await page.screenshot({path:info.outputPath(`captured-research-panel-${width}.png`),fullPage:true});
  await page.goto(financialUrl);
  await page.getByRole('button',{name:'编辑批注',exact:true}).click();
  await page.getByLabel('编辑来源批注').fill(`修订批注 ${width}：先分别核对年度与季度。`);
  await page.getByRole('button',{name:'保存批注版本',exact:true}).click();
  await expect(page.getByRole('status').filter({hasText:'批注已保存新版本'})).toBeVisible();
  await expect(page.getByLabel('固定来源与批注')).toContainText(`修订批注 ${width}`);
  await page.reload();
  await expect(page.getByLabel('固定来源与批注')).toContainText(`修订批注 ${width}`);
  const newVersion=new URL(page.url()).searchParams.get('asset');expect(newVersion).not.toBe(version);
  const old=await(await page.request.get(`/api/v1/research-sessions/${tid}`)).json();
  expect(old.asset_context.refs).toEqual(task.asset_context.refs);
  expect(old.attachments.find((a:any)=>a.project_origin.asset_capture.kind==='financial').project_origin.document_id).toBe(version);
  await page.goto(financialUrl);
  await expect(page.getByLabel('固定来源与批注')).toContainText(`原始批注 ${width}`);
  await expect(page.getByText('正在查看历史版本。准备任务时会明确绑定这一版。')).toBeVisible();
  expect(errors).toEqual([]);
});
