import {test,expect} from 'playwright/test';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';

// Operator-supplied real saved sources. No synthetic corpus substitutes for this check.
for(const width of [1440,900,390])test(`真实知识库数据库与项目侧栏 ${width}`,async({page},info)=>{
  test.skip(!process.env.FIN_ASSET_LIBRARY_SETTINGS,'Requires an explicit local real-data snapshot');
  test.setTimeout(90000);
  const evidence=JSON.parse(readFileSync(resolve(process.env.FINSIGHT_LOCAL_STATE_ROOT!,'source-manifest.json'),'utf8'));
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.setViewportSize({width,height:960});
  await page.addInitScript(()=>{if(!localStorage.getItem('finsight.theme'))localStorage.setItem('finsight.theme','light');});
  await page.goto('/workspace/assets');
  await expect(page.getByRole('heading',{name:'知识库',exact:true})).toBeVisible();
  await expect(page.locator('.dl-summary strong')).toHaveText(`${evidence.documents} 份公共资料`);
  await expect(page.locator('.dl-card')).toHaveCount(24);
  const palette=await page.locator('.fs-workspace').evaluate(e=>{const s=getComputedStyle(e);return [s.fontFamily,s.getPropertyValue('--accent'),s.getPropertyValue('--surface')];});
  await page.screenshot({path:info.outputPath(`knowledge-${width}.png`),fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
  await page.getByRole('button',{name:'下一页',exact:true}).click();
  await expect(page.getByText('第 2 页',{exact:true})).toBeVisible();
  await page.getByLabel('公司',{exact:true}).selectOption('MSFT');
  const sourceResponse=await page.request.get('/api/v1/data-library/sources?ticker=MSFT');
  const source=(await sourceResponse.json()).items[0];
  await expect(page.locator('.dl-card').first()).toContainText(source.title.replace('earnings_release','业绩新闻稿'));
  await page.locator('.dl-card').first().click();
  await expect(page.getByRole('dialog',{name:'公共资料阅读'})).toBeVisible();
  await expect(page.locator('.dl-reading section').first()).toBeVisible();
  expect((await page.locator('.dl-reading').innerText()).length).toBeGreaterThan(200);
  await expect(page.getByRole('link',{name:'打开官方原文'})).toHaveAttribute('href',source.stable_url);
  await page.screenshot({path:info.outputPath(`knowledge-reader-${width}.png`),fullPage:true});
  await page.getByRole('button',{name:'关闭公共资料',exact:true}).click();
  await page.getByRole('button',{name:'财务数据库',exact:true}).click();
  await expect(page).toHaveURL(/workspace\/assets\?view=financial-data/);
  await expect(page.locator('.dl-summary strong')).toHaveText(`${evidence.financial_rows} 条披露记录`);
  await page.getByLabel('公司',{exact:true}).selectOption('MSFT');
  await page.getByLabel('指标',{exact:true}).selectOption('revenue');
  await expect(page.locator('.dl-table tbody tr').first()).toContainText(evidence.sample_msft_revenue.value_decimal);
  await expect(page.locator('.dl-table tbody tr').first()).toContainText(evidence.sample_msft_revenue.unit);
  await expect(page.locator('.dl-table tbody tr').first()).toContainText(evidence.sample_msft_revenue.period_end);
  await page.screenshot({path:info.outputPath(`database-${width}.png`),fullPage:true});
  await page.getByLabel('披露截至日期').fill('1900-01-01');
  await expect(page.locator('.dl-summary strong')).toHaveText('0 条披露记录');
  await expect(page.getByRole('heading',{name:'当前筛选范围尚无资料'})).toBeVisible();
  await page.goto('/workspace/session?view=library');
  await expect(page).toHaveURL(/workspace\/assets\?view=library/);

  const index=await(await page.request.get('/api/v1/projects')).json();
  const project=index.projects[0].id;
  const catalog=await(await page.request.get(`/api/v1/asset-workspace/projects/${project}`)).json();
  const ref=catalog.items[0].current.ref;
  const made=await page.request.post('/api/v1/research-sessions',{headers:{'X-Workbench-Request':'1'},data:{mode:'research',defer_start:true,question:`核对已保存披露的期间与来源，不进行模型调用。${width}`,project_materials:{project_id:project,document_ids:[ref.version_id]}}});
  expect(made.ok()).toBe(true);const tid=(await made.json()).thread_id;
  await page.goto(`/workspace/session?thread=${tid}&view=graph`);
  const researchPalette=await page.locator('.fs-workspace').evaluate(e=>{const s=getComputedStyle(e);return [s.fontFamily,s.getPropertyValue('--accent'),s.getPropertyValue('--surface')];});
  expect(researchPalette).toEqual(palette);
  await page.getByRole('button',{name:'项目资料',exact:true}).click();
  const panel=page.getByRole('complementary',{name:'项目资料侧栏'});
  await expect(panel).toBeVisible();await expect(page.getByLabel('侧栏资料正文')).toContainText('Microsoft');
  expect(new URL(page.url()).searchParams.get('thread')).toBe(tid);
  await page.screenshot({path:info.outputPath(`project-panel-${width}.png`),fullPage:true});
  await panel.getByRole('link',{name:'在资产区打开与编辑'}).click();
  await expect(page.getByLabel('资产正文')).toContainText('Microsoft');
  await page.getByRole('button',{name:'编辑',exact:true}).click();
  const text=await page.getByLabel('资产内容').inputValue();
  await page.getByLabel('资产内容').fill(text+`\n\n用户验收补记 ${width}：这是项目阅读副本，未修改公共原件。`);
  await page.getByRole('button',{name:'保存版本',exact:true}).click();
  await expect(page.getByLabel('资产正文')).toContainText(`用户验收补记 ${width}`);
  await page.reload();
  await expect(page.getByLabel('资产正文')).toContainText(`用户验收补记 ${width}`);
  await page.getByRole('link',{name:'返回研究',exact:true}).click();
  expect(new URL(page.url()).searchParams.get('thread')).toBe(tid);
  await page.getByRole('button',{name:'项目资料',exact:true}).click();
  await expect(page.getByLabel('侧栏资料正文')).toContainText(`用户验收补记 ${width}`);
  const task=await(await page.request.get(`/api/v1/research-sessions/${tid}`)).json();
  expect(task.attachments[0].project_origin.document_id).toBe(ref.version_id);
  expect(task.runs).toEqual([]);
  await page.getByRole('button',{name:'关闭项目资料侧栏',exact:true}).click();
  await expect(panel).toHaveCount(0);
  await page.evaluate(()=>localStorage.setItem('finsight.theme','dark'));
  await page.goto('/workspace/assets?view=financial-data');
  await expect(page.locator('.dl-table tbody tr').first()).toBeVisible();
  const dark=await page.locator('.fs-workspace').evaluate(e=>getComputedStyle(e).getPropertyValue('--surface'));
  expect(dark).not.toBe(palette[2]);
  await page.screenshot({path:info.outputPath(`assets-dark-${width}.png`),fullPage:true});
  await page.goto('/workspace/session');
  expect(await page.locator('.fs-workspace').evaluate(e=>getComputedStyle(e).getPropertyValue('--surface'))).toBe(dark);
  expect(errors).toEqual([]);
});
